POST http://localhost:5001/api/users/registration HTTP/1.1
Content-Type: application/json

{
  "email": "john.doe@gmail.com",
  "passwordHash": "qwerty123",
  "firstName": "John",
  "lastName": "Doe",
  "birthday": "1986-12-25"
}